Repository geany/geany, pull requests merged in 2019-08, with the labels that each got.

#2250 Add support for fractional font sizes (superseeds #407)
  src/editor.c
  src/sciwrappers.c
  src/sciwrappers.h
Labels: enhancement, reviewed, scintilla, tested

#2163 Show the GTK/GLib versions in about dialog
  src/about.c
Labels: enhancement, existing capability, gtk

#2256 build.c: ASSIGNIF -> assign_cmd
  src/build.c
Labels: enhancement
