Repository geany/geany, pull requests merged in 2019-10, with the labels that each got.

#2114 Save main and project configuration whenever documents are opened/closed
  doc/geany.txt
  doc/pluginsignals.c
  src/document.h
  src/keyfile.c
Labels: enhancement

#2337 doc: added documentation for the Color Chooser
  doc/geany.txt
Labels: documentation

#2212 added a bibtex parser that extracts identifiers of entries in bib-fil…
  ctags/Makefile.am
  ctags/main/parsers.h
  ctags/parsers/bibtex.c
  data/Makefile.am
  data/filedefs/filetypes.bibtex
  data/filetype_extensions.conf
  src/filetypes.c
  src/filetypes.h
  src/symbols.c
  src/tagmanager/tm_parser.c
  src/tagmanager/tm_parser.h
Labels: ctags parser, enhancement, filetype
