Repository geany/geany, pull requests merged in 2019-01, with the labels that each got.

#2032 Fix modifier for creating rectangular selections on Windows
  src/editor.c
Labels: scintilla, windows

#2045 Update Scintilla to version 3.10.2
  scintilla/gtk/ScintillaGTK.cxx
  scintilla/gtk/ScintillaGTKAccessible.cxx
  scintilla/include/Platform.h
  scintilla/include/SciLexer.h
  scintilla/include/Scintilla.h
  scintilla/include/Scintilla.iface
  scintilla/lexers/LexBash.cxx
  scintilla/lexers/LexCPP.cxx
  scintilla/lexers/LexFortran.cxx
  scintilla/lexers/LexMarkdown.cxx
  scintilla/lexers/LexVerilog.cxx
  scintilla/lexlib/CharacterCategory.cxx
  scintilla/lexlib/PropSetSimple.cxx
  scintilla/scintilla_changes.patch
  scintilla/src/CaseConvert.cxx
  scintilla/src/Catalogue.cxx
  scintilla/src/CellBuffer.cxx
  scintilla/src/CellBuffer.h
  scintilla/src/ContractionState.cxx
  scintilla/src/Document.cxx
  scintilla/src/Document.h
  scintilla/src/EditModel.cxx
  scintilla/src/EditView.cxx
  scintilla/src/Editor.cxx
  scintilla/src/Editor.h
  scintilla/src/ExternalLexer.cxx
  scintilla/src/Indicator.cxx
  scintilla/src/KeyMap.cxx
  scintilla/src/KeyMap.h
  scintilla/src/PerLine.cxx
  scintilla/src/PositionCache.cxx
  scintilla/src/PositionCache.h
  scintilla/src/RESearch.cxx
  scintilla/src/RunStyles.cxx
  scintilla/src/ScintillaBase.cxx
  scintilla/src/Style.cxx
  scintilla/src/UniConversion.cxx
  scintilla/src/UniConversion.h
  scintilla/src/ViewStyle.cxx
  scintilla/version.txt
Labels: scintilla

#2036 Show variable type in a tooltip in symbol tree
  src/symbols.c
Labels: enhancement
