Repository geany/geany, pull requests merged in 2020-10, with the labels that each got.

#2597 Persist colour picker palette
  src/keyfile.c
  src/libmain.c
  src/tools.c
  src/ui_utils.h
Labels: enhancement, gtk

#2610 Make GTK3 build the default, and GTK2 build optional
  .travis.yml
  configure.ac
  scripts/cross-build-mingw.sh
Labels: gtk

#2613 Fix gtk2/gtk3 mac integration test
  m4/geany-mac-integration.m4
Labels: macos

#2399 Add Smalltalk filetype
  data/Makefile.am
  data/filedefs/filetypes.smalltalk
  data/filetype_extensions.conf
  scintilla/Makefile.am
  scintilla/lexers/LexSmalltalk.cxx
  scintilla/scintilla_changes.patch
  scintilla/src/Catalogue.cxx
  src/filetypes.c
  src/filetypes.h
  src/highlighting.c
  src/highlightingmappings.h
Labels: filetype

#2333 Define text color when setting dark background in find dialog
  data/geany.css
  data/geany.gtkrc
Labels: gtk-theme

#2223 Allow to select the Python command, and use `py` on Windows
  configure.ac
  data/Makefile.am
  data/filedefs/filetypes.python.in
Labels: enhancement, filetype, windows

#2618 OS Info Improvements
  src/libmain.c
  src/utils.c
  src/utils.h
Labels: enhancement

#1738 Size symbols and fold margins proportional to line height
  data/filedefs/filetypes.common
  src/editor.c
  src/highlighting.c
  src/sciwrappers.c
  src/sciwrappers.h
Labels: enhancement
