Repository geany/geany, pull requests merged in 2021-09, with the labels that each got.

#2885 Use "encoding" keyword argument for lxml's tostring()
  scripts/gen-api-gtkdoc.py
Labels: build-system

#2862 Update C++ compiler check to require C++17
  configure.ac
  m4/ax_cxx_compile_stdcxx.m4
  m4/ax_cxx_compile_stdcxx_11.m4
  m4/ax_cxx_compile_stdcxx_17.m4
Labels: enhancement, scintilla, tested, packaging, build-system

#2850 add @mesonbuild filetype support
  data/Makefile.am
  data/filedefs/filetypes.Meson.conf
  data/filetype_extensions.conf
Labels: enhancement, filetype
