Repository geany/geany, pull requests merged in 2023-04, with the labels that each got.

#3443 Prevent possible crash when using tm_workspace API by plugins
  src/tagmanager/tm_workspace.c
Labels: tag-manager

#3405 Update CLI filenames docs
  doc/geany.txt
Labels: documentation

#3400 Tweak templates/snippets docs
  doc/geany.txt
Labels: documentation

#2355 docs: Document Open dialog options
  doc/geany.txt
Labels: documentation

#3432 CI: Define JOBS environment variable and use it for make
  .github/workflows/build.yml
Labels: build-system

#1752 Add AutoIt syntax highlighting and Ctags parser for AutoIt
  ctags/Makefile.am
  ctags/parsers/autoit.c
  data/Makefile.am
  data/filedefs/filetypes.autoit
  data/filetype_extensions.conf
  meson.build
  scintilla/Makefile.am
  scintilla/lexilla/lexers/LexAU3.cxx
  scintilla/lexilla/src/Lexilla.cxx
  scintilla/scintilla_changes.patch
  src/filetypes.c
  src/filetypes.h
  src/highlighting.c
  src/highlightingmappings.h
  src/tagmanager/tm_parser.c
  src/tagmanager/tm_parser.h
  src/tagmanager/tm_parsers.h
  tests/ctags/Makefile.am
  tests/ctags/simple.au3
  tests/ctags/simple.au3.tags
  tests/meson.build
Labels: enhancement, filetype

#3470 Add docs for calltips
  doc/geany.txt
Labels: documentation
