Repository geany/geany, pull requests merged in 2023-10, with the labels that each got.

#3535 Fix crash closing directory from the openfiles sidebar
  src/sidebar.c
Labels: bug, crash

#3568 CI: Use mingw posix crosscompiler
  scripts/ci_mingw64_geany.sh
Labels: build-system

#3594 CI: Fix version parsing and calculating for 2.0
  scripts/ci_mingw64_geany.sh
Labels: build-system

#3129 Windows: Include "Prof-Gnome" GTK theme from geany-osx
  scripts/gtk-bundle-from-msys2.sh
Labels: windows

#3600 Link to libiconv explicitly for Windows/mingw64 builds
  configure.ac
Labels: windows, build-system

#3604 Fix blooper leading to incorrect variable formatting
  src/tagmanager/tm_parser.c
Labels: bug

#3049 Use the official 'libreadtags' library from ctags for parsing ctags files
  ctags/Makefile.am
  ctags/libreadtags/readtags.c
  ctags/libreadtags/readtags.h
  doc/geany.txt
  meson.build
  src/tagmanager/Makefile.am
  src/tagmanager/tm_source_file.c
  src/tagmanager/tm_tag.h
Labels: tag-manager

#3611 Fix startup files order when placing tabs next to the current one
  src/keyfile.c
  src/notebook.c
Labels: bug

#3616 Fix crash opening an AsciiDoc document
  scintilla/lexilla/src/Lexilla.cxx
  scintilla/scintilla_changes.patch
  src/sciwrappers.c
Labels: bug, crash

#3593 Release 2.0 documentation
  NEWS
  doc/Makefile.am
  doc/geany.txt
  doc/images/build_menu_commands_dialog.png
  doc/images/edit_change_history.png
  doc/images/find_dialog.png
  doc/images/find_in_files_dialog.png
  doc/images/main_window.png
  doc/images/pref_dialog_edit_completions.png
  doc/images/pref_dialog_edit_display.png
  doc/images/pref_dialog_edit_features.png
  doc/images/pref_dialog_edit_indentation.png
  doc/images/pref_dialog_files.png
  doc/images/pref_dialog_gen_misc.png
  doc/images/pref_dialog_gen_startup.png
  doc/images/pref_dialog_interface_interface.png
  doc/images/pref_dialog_interface_notebook.png
  doc/images/pref_dialog_interface_toolbar.png
  doc/images/pref_dialog_keys.png
  doc/images/pref_dialog_printing.png
  doc/images/pref_dialog_templ.png
  doc/images/pref_dialog_tools.png
  doc/images/pref_dialog_various.png
  doc/images/pref_dialog_vte.png
  doc/images/replace_dialog.png
  doc/meson.build
Labels: documentation

#3634 Enable translations in the "Various" tab in preferences dialog
  src/stash.c
Labels: translations

#3633 Add meson.build to release howto and replace IRC by Matrix
  doc/making-a-release
Labels: documentation

#3636 Update da.po
  po/da.po
Labels: translations
