Repository geany/geany, pull requests merged in 2024-06, with the labels that each got.

#3885 Windows: Add glib-compile-schemas.exe to GTK bundle
  geany.nsi.in
  scripts/gtk-bundle-from-msys2.sh
Labels: windows

#3833 [build] Improve custom command dialog
  src/build.c
  src/dialogs.c
Labels: build-system

#3650 Autotools: regenerate gmo files when po files are updated
  po/Rules-gmo
Labels: i18n, build-system

#3572 Add "document-before-save-as" signal
  doc/pluginsignals.c
  src/document.c
  src/geanyobject.c
  src/geanyobject.h
Labels: lsp

#3877 Update ctags to p6.1.20240519.0
  ctags/libreadtags/readtags.c
  ctags/libreadtags/readtags.h
  ctags/main/repoinfo.h
  ctags/parsers/jscript.c
  ctags/parsers/matlab.c
  ctags/parsers/pascal.c
  ctags/parsers/powershell.c
  scripts/update-ctags.py
  src/tagmanager/tm_parser.c
  tests/ctags/enum.ps1.tags
  tests/ctags/matlab_backtracking.m.tags
  tests/ctags/matlab_test.m.tags
Labels: ctags parser

#3903 Drop win32_message_dialog()s
  src/dialogs.c
  src/win32.c
  src/win32.h
Labels: windows

#3823 [RFC] Enable keyboard searching for Compiler and Messages tree views
  src/msgwindow.c
Labels: enhancement

#3916 Export some types/functions so plugins have access to Geany symbol icons
  src/symbols.c
  src/symbols.h
  src/tagmanager/tm_parser.h
Labels: lsp
