Repository geany/geany, pull requests merged in 2025-06, with the labels that each got.

#4319 prefs: Migrate pre-2.1 print_cmd format
  src/keyfile.c
Labels: bug

#4318 Fix %p build placeholder, and various placeholder replacement fixes and improvements
  data/geany.glade
  doc/geany.txt
  src/build.c
  src/callbacks.c
  src/document.c
  src/editor.c
  src/keybindings.c
  src/prefs.c
  src/printing.c
  src/ui_utils.c
  src/ui_utils.h
  src/utils.c
  src/utils.h
  tests/test_utils.c
Labels: enhancement, bug

#4322 Drop win32_open_browser()
  src/keyfile.c
  src/prefs.c
  src/utils.c
  src/win32.c
  src/win32.h
Labels: windows

#4337 Cobol: Use SCE_COBOL_* defines for highlighting mappings
  data/filedefs/filetypes.cobol
  src/highlightingmappings.h
Labels: filetype

#4334 Increase line number margin default width
  src/sciwrappers.c
Labels: enhancement

#4347 Update of Slovak translation
  po/sk.po
Labels: translations
