Repository geany/geany, pull requests merged in 2025-02, with the labels that each got.

#4181 Use builtin regex on macOS for performance reasons
  configure.ac
  meson.build
Labels: macos

#4204 Workaround incorrect scaling of "reverse arrow" cursor under Windows and HiDPI screens
  scintilla/gtk/PlatGTK.cxx
Labels: windows

#4205 Use themed title bar on Windows
  src/search.c
  src/ui_utils.c
  src/win32.c
  src/win32.h
Labels: enhancement, windows

#4226 Fix #4192 aftermath :boom: (sorry @eht16 :grin:)
  src/prefs.c
Labels: bug, crash

#4243 CI: Update to Ubuntu 22.04 runners as 20.04 are getting deprecated
  .github/workflows/build.yml
Labels: build-system

#4246 Add new filetype and ctags parser for Terraform HCL language
  ctags/Makefile.am
  ctags/optlib/terraform.c
  data/Makefile.am
  data/filedefs/filetypes.HCL.conf
  data/filetype_extensions.conf
  meson.build
  src/tagmanager/tm_parser.c
  src/tagmanager/tm_parser.h
  src/tagmanager/tm_parsers.h
  tests/ctags/Makefile.am
  tests/ctags/simple.tf
  tests/ctags/simple.tf.tags
  tests/meson.build
Labels: filetype, ctags parser
