Repository geany/geany, pull requests merged in 2025-01, with the labels that each got.

#4088 Windows add new dependencies
  scripts/ci_mingw64_geany.sh
  scripts/gtk-bundle-from-msys2.sh
Labels: windows

#4190 Windows: Let "curl" retry package downloads and show errors
  scripts/gtk-bundle-from-msys2.sh
Labels: windows, build-system

#3934 Add TOML support
  ctags/parsers/iniconf.c
  data/Makefile.am
  data/filedefs/filetypes.toml
  data/filetype_extensions.conf
  meson.build
  scintilla/Makefile.am
  scintilla/lexilla/lexers/LexTOML.cxx
  scintilla/lexilla/src/Lexilla.cxx
  scintilla/scintilla_changes.patch
  src/filetypes.c
  src/filetypes.h
  src/highlighting.c
  src/highlightingmappings.h
Labels: filetype

#4095 Add support for SCSS/LESS
  ctags/Makefile.am
  ctags/optlib/scss.c
  data/Makefile.am
  data/filedefs/filetypes.LESS.conf
  data/filedefs/filetypes.SCSS.conf
  data/filetype_extensions.conf
  meson.build
  src/tagmanager/tm_parser.c
  src/tagmanager/tm_parser.h
  src/tagmanager/tm_parsers.h
  tests/ctags/Makefile.am
  tests/ctags/simple.scss
  tests/ctags/simple.scss.tags
  tests/meson.build
Labels: filetype

#4192 Add filter for keybindings in preferences dialog
  data/geany.glade
  src/plugins.c
  src/prefs.c
  src/utils.c
  src/utils.h
Labels: enhancement

#4210 Add filter for open documents sidebar item
  data/geany.glade
  doc/geany.txt
  src/callbacks.c
  src/callbacks.h
  src/document.c
  src/sidebar.c
  src/sidebar.h
Labels: enhancement
